[package]
name = "cordis"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", default-features = false, features = ["rt", "time"], optional = true }

[features]
default = ["tokio"]

[dev-dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time", "macros"] }

[[example]]
name = "tasks"
required-features = ["tokio"]
